# Generated by Django 3.0.8 on 2023-08-08 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20230418_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic',
            name='degree',
            field=models.CharField(max_length=200, null=True, verbose_name='Degree/Certificate'),
        ),
        migrations.AlterField(
            model_name='academic',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='faculty',
            field=models.CharField(blank=True, choices=[(None, 'Select Faculty'), ('fac-1', 'ARTS'), ('fac-2', 'SCIENCE'), ('fac-3', 'ENGINEERING & TECHNOLOGY'), ('fac-4', 'ISLM'), ('fac-5', 'ENGINEERING')], max_length=100, null=True, verbose_name='Faculty :'),
        ),
        migrations.AlterField(
            model_name='apicatg_i',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apicatg_ii',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orientation',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='presentpost',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='priorpost',
            name='dt_join',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of Joining'),
        ),
        migrations.AlterField(
            model_name='priorpost',
            name='dt_leav',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of Leaving'),
        ),
        migrations.AlterField(
            model_name='priorpost',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='priorpost',
            name='gross_salary',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Gross Salary'),
        ),
        migrations.AlterField(
            model_name='research',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='research',
            name='institute',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name of the Board/University'),
        ),
        migrations.AlterField(
            model_name='research',
            name='url_link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Put your document link'),
        ),
        migrations.AlterField(
            model_name='teachingexp',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
