# Generated by Django 4.2.4 on 2024-07-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_academic_id_alter_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priorpost',
            name='designation',
            field=models.CharField(blank=True, choices=[(None, 'Select'), ('Stage 1', 'Assistant Professor - Stage 1'), ('Stage 2', 'Assistant Professor - Stage 2'), ('Stage 3', 'Assistant Professor - Stage 3'), ('Stage 4', 'Assistant Professor - Stage 4'), ('Stage 5', 'Professor - Stage 5')], max_length=400, null=True, verbose_name='Designation'),
        ),
    ]
