# Generated by Django 4.2.4 on 2024-05-23 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_feedback_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
