# Generated by Django 4.2.4 on 2024-05-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_delete_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=255)),
                ('year', models.CharField(choices=[('1st', '1st Year'), ('2nd', '2nd Year')], max_length=10)),
                ('semester', models.CharField(choices=[('1st', '1st Semester'), ('2nd', '2nd Semester')], max_length=10)),
                ('fb_dt', models.DateField()),
                ('students_no', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
