# Generated by Django 4.2.4 on 2024-06-10 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_academic_id_alter_account_id_and_more'),
        ('voting', '0006_courses_delete_facultyid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=100)),
                ('faculty_email', models.EmailField(max_length=60, unique=True)),
                ('faculty_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('emp_id', models.CharField(max_length=6, unique=True)),
                ('year', models.CharField(blank=True, choices=[(None, 'Select'), ('1', '1st'), ('2', '2nd')], max_length=6, null=True)),
                ('semestar', models.CharField(blank=True, choices=[(None, 'Select'), ('1', '1st'), ('2', '2nd')], max_length=6, null=True)),
                ('batch', models.CharField(blank=True, choices=[(None, 'Select'), ('1', '2020-21'), ('2', '2021-22'), ('3', '2022-23'), ('4', '2023-24')], max_length=6, null=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('course_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.courses')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_members', to='account.department')),
            ],
        ),
    ]
