# Generated by Django 4.2.4 on 2024-06-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='emp_id',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_email',
            field=models.EmailField(max_length=60),
        ),
    ]
